Repository knative-extensions/autoscaler-keda, pull requests merged in 2024-12, with the labels that each got.

#84 RevisionName templating and substitution.
  pkg/reconciler/autoscaling/hpa/resources/keda.go
  pkg/reconciler/autoscaling/hpa/resources/keda_test.go
  test/e2e/autoscale_custom_test.go
  test/e2e/helpers.go
  test/test_images/metrics-test/service_revision_name_template.yaml
Labels: kind/enhancement, lgtm, size/L, approved, ok-to-test, kind/documentation

#89 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#91 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
