Repository knative-extensions/autoscaler-keda, pull requests merged in 2024-09, with the labels that each got.

#44 Fix kube codegen
  hack/update-codegen.sh
Labels: size/S, lgtm, approved

#45 Debug codegen
  hack/patches/debug.patch
  hack/update-deps.sh
  vendor/knative.dev/hack/codegen-library.sh
Labels: size/S, lgtm, approved

#46 Revert "Debug codegen (#45)"
  hack/patches/debug.patch
  hack/update-deps.sh
  vendor/knative.dev/hack/codegen-library.sh
Labels: size/S, lgtm, approved

#48 Added the section of prometheus-node-exporter.hostRootFsMount to helm
  DEVELOPMENT.md
  values.yaml
Labels: size/XS, lgtm, approved

#47 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#49 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#51 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_hurd.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_zos_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/term_windows.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#53 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/internal/aliases/aliases.go
  vendor/golang.org/x/tools/internal/aliases/aliases_go121.go
  vendor/golang.org/x/tools/internal/aliases/aliases_go122.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/internal/pkgbits/encoder.go
  vendor/golang.org/x/tools/internal/pkgbits/frames_go1.go
  vendor/golang.org/x/tools/internal/pkgbits/frames_go17.go
  vendor/golang.org/x/tools/internal/pkgbits/support.go
  vendor/golang.org/x/tools/internal/pkgbits/sync.go
  vendor/golang.org/x/tools/internal/pkgbits/syncmarker_string.go
  vendor/golang.org/x/tools/internal/pkgbits/version.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  vendor/google.golang.org/grpc/experimental/stats/metricregistry.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/mem/buffer_slice.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#58 Fix target name
  pkg/reconciler/autoscaling/hpa/resources/keda.go
  pkg/reconciler/autoscaling/hpa/resources/keda_test.go
  pkg/reconciler/autoscaling/hpa/resources/scaled_object.go
Labels: lgtm, size/M, approved, kind/bug

#55 Support scale to zero
  pkg/reconciler/autoscaling/hpa/resources/keda.go
  test/e2e-tests.sh
  test/e2e/autoscale_custom_test.go
  test/e2e/helpers.go
  test/test_images/metrics-test/main.go
Labels: kind/enhancement, lgtm, size/L, approved

#60 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/crd.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#62 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#63 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e/httpproxy.go
  vendor/modules.txt
Labels: size/S, lgtm, approved
