Repository knative-extensions/autoscaler-keda, pull requests merged in 2024-08, with the labels that each got.

#39 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#35 Allow more options
  CONCEPTS-API.md
  pkg/reconciler/autoscaling/hpa/helpers/helpers.go
  pkg/reconciler/autoscaling/hpa/keda_hpa.go
  pkg/reconciler/autoscaling/hpa/keda_hpa_test.go
  pkg/reconciler/autoscaling/hpa/resources/keda.go
  pkg/reconciler/autoscaling/hpa/resources/keda_test.go
  pkg/reconciler/autoscaling/hpa/resources/scaled_object.go
  test/test_images/metrics-test/service_cpu.yaml
  test/test_images/metrics-test/service_memory.yaml
  test/test_images/metrics-test/service_multiple_triggers.yaml
  test/test_images/metrics-test/service_multiple_triggers_scaling_modifiers.yaml
  vendor/knative.dev/serving/pkg/reconciler/autoscaling/hpa/resources/hpa.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#40 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/golang.org/x/sync/LICENSE
  vendor/modules.txt
Labels: lgtm, size/M, approved

#41 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
