Repository knative-extensions/autoscaler-keda, pull requests merged in 2024-07, with the labels that each got.

#19 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#24 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_asm.go
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand_go1.21.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/dns/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#23 Fix release script
  hack/release.sh
  test/e2e-tests.sh
Labels: lgtm, size/M, approved, kind/bug

#28 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#27 Add autoscaler-keda configmap
  config/config.yaml
  go.mod
  hack/update-codegen.sh
  pkg/reconciler/autoscaling/hpa/config/autoscaler_keda.go
  pkg/reconciler/autoscaling/hpa/config/autoscaler_keda_test.go
  pkg/reconciler/autoscaling/hpa/config/doc.go
  pkg/reconciler/autoscaling/hpa/config/store.go
  pkg/reconciler/autoscaling/hpa/config/store_test.go
  pkg/reconciler/autoscaling/hpa/config/testdata/config-autoscaler-keda.yaml
  pkg/reconciler/autoscaling/hpa/config/testdata/config-autoscaler.yaml
  pkg/reconciler/autoscaling/hpa/config/zz_generated.deepcopy.go
  pkg/reconciler/autoscaling/hpa/controller.go
  pkg/reconciler/autoscaling/hpa/keda_hpa.go
  pkg/reconciler/autoscaling/hpa/keda_hpa_test.go
  pkg/reconciler/autoscaling/hpa/resources/keda.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#29 Adds support for KEDA auth
  OPENSHIFT.md
  README.md
  pkg/reconciler/autoscaling/hpa/config/autoscaler_keda.go
  pkg/reconciler/autoscaling/hpa/helpers/helpers.go
  pkg/reconciler/autoscaling/hpa/keda_hpa.go
  pkg/reconciler/autoscaling/hpa/keda_hpa_test.go
  pkg/reconciler/autoscaling/hpa/resources/keda.go
  pkg/reconciler/autoscaling/hpa/resources/keda_test.go
  pkg/reconciler/autoscaling/hpa/resources/scaled_object.go
Labels: lgtm, approved, size/XXL

#30 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#31 BYO scaledobject
  DEVELOPMENT.md
  config/config.yaml
  pkg/reconciler/autoscaling/hpa/config/autoscaler_keda.go
  pkg/reconciler/autoscaling/hpa/keda_hpa.go
  pkg/reconciler/autoscaling/hpa/resources/keda.go
  pkg/reconciler/autoscaling/hpa/resources/keda_test.go
  test/e2e/autoscale_custom_test.go
Labels: lgtm, size/L, approved

#34 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#37 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
