Repository knative-extensions/autoscaler-keda, pull requests merged in 2025-01, with the labels that each got.

#93 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#99 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#100 [RELEASE-1.16] Fix cloned branch in tests
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#97 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#103 Fix gengo issue
  .github/workflows/workflows/knative-go-build.yaml
  .github/workflows/workflows/knative-go-test.yaml
  .github/workflows/workflows/knative-security.yaml
  .github/workflows/workflows/knative-stale.yaml
  .github/workflows/workflows/knative-style.yaml
  .github/workflows/workflows/knative-verify.yaml
  go.mod
  vendor/modules.txt
Labels: lgtm, size/L, approved

#108 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#110 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
